# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.10.0
_src_path: gh:radio-aktywne/template-package-python
accountname: radio-aktywne
description: Locking utilities package for Python 🐍
docs: true
docsurl: https://radio-aktywne.github.io/pylocks
importname: pylocks
packagename: pylocks
releases: true
reponame: pylocks
repourl: https://github.com/radio-aktywne/pylocks
